# Generated by Django 4.2 on 2023-05-15 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoncesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='title', max_length=100, unique=True)),
                ('postdate', models.DateField(blank=True, default=datetime.datetime(2023, 5, 15, 14, 54, 48, 507362, tzinfo=datetime.timezone.utc), null=True)),
                ('updated', models.DateField(blank=True, default=datetime.datetime(2023, 5, 15, 14, 54, 48, 507362, tzinfo=datetime.timezone.utc), null=True)),
                ('text', models.CharField(max_length=700)),
                ('link', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoursModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulenom', models.CharField(default='module', max_length=55)),
                ('name', models.CharField(default='chapitre', max_length=55)),
                ('file', models.FileField(null=True, upload_to='templet/files/')),
            ],
        ),
        migrations.CreateModel(
            name='EncadrementDesLicenceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SujetsDesPFE', models.CharField(max_length=700)),
                ('EtudiantsConcernes', models.CharField(default='#', max_length=100)),
                ('Filiere', models.CharField(default='(SMI S6) 2020/2021', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EncadrementDesMAasterModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nom', max_length=100, unique=True)),
                ('SujetsDesPFE', models.CharField(max_length=700)),
                ('AnneeInscription', models.CharField(default='(2019-2021)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EncadrementDesThesesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctorant', models.CharField(default='#', max_length=50, unique=True)),
                ('Sujet', models.CharField(max_length=700)),
                ('AnneeInscription', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamensModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulenom', models.CharField(default='module', max_length=55)),
                ('name', models.CharField(default='examen', max_length=55)),
                ('file', models.FileField(null=True, upload_to='templet/files/')),
            ],
        ),
        migrations.CreateModel(
            name='moduleModels',
            fields=[
                ('modulenom', models.CharField(default='module', max_length=55, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulenom', models.CharField(default='module', max_length=55)),
                ('name', models.CharField(default='Series', max_length=55)),
                ('file', models.FileField(null=True, upload_to='templet/files/')),
            ],
        ),
        migrations.CreateModel(
            name='tokenModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundColorType', models.CharField(default='normele', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
