# Generated by Django 4.2 on 2023-05-18 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_coursmodels_module_examensmodels_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesmodels',
            name='modulenom',
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='postdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 18, 17, 35, 32, 87624, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='updated',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 18, 17, 35, 32, 87624, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
