# Generated by Django 4.2 on 2023-05-18 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_annoncesmodels_postdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursmodels',
            name='modulenom',
        ),
        migrations.RemoveField(
            model_name='examensmodels',
            name='modulenom',
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='postdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 18, 18, 11, 33, 863362, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='updated',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 18, 18, 11, 33, 863362, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
