# Generated by Django 4.2 on 2023-05-18 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_seriesmodels_modulenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncesmodels',
            name='postdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 18, 18, 8, 30, 529908, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='updated',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 18, 18, 8, 30, 529908, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='seriesmodels',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.modulemodels'),
        ),
    ]
