# Generated by Django 4.2 on 2023-05-28 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_annoncesmodels_postdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmodels',
            name='postdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 28, 17, 6, 51, 103013, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='postdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 28, 17, 6, 51, 105006, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='updated',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 28, 17, 6, 51, 105006, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
