# Generated by Django 4.2 on 2023-05-28 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_tokenmodels_postdate_alter_annoncesmodels_postdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncesmodels',
            name='postdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 28, 17, 7, 54, 488587, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='annoncesmodels',
            name='updated',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 28, 17, 7, 54, 488587, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='tokenmodels',
            name='postdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
