# Generated by Django 4.2 on 2023-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_annoncesmodels_postdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncesmodels',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
